# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: variant_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import variants_pb2 as variants__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='variant_service.proto',
  package='ga4gh',
  syntax='proto3',
  serialized_pb=b'\n\x15variant_service.proto\x12\x05ga4gh\x1a\x0evariants.proto\"U\n\x18SearchVariantSetsRequest\x12\x12\n\ndataset_id\x18\x01 \x01(\t\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t\"]\n\x19SearchVariantSetsResponse\x12\'\n\x0cvariant_sets\x18\x01 \x03(\x0b\x32\x11.ga4gh.VariantSet\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\".\n\x14GetVariantSetRequest\x12\x16\n\x0evariant_set_id\x18\x01 \x01(\t\"\xa0\x01\n\x15SearchVariantsRequest\x12\x16\n\x0evariant_set_id\x18\x01 \x01(\t\x12\x14\n\x0c\x63\x61ll_set_ids\x18\x02 \x03(\t\x12\x16\n\x0ereference_name\x18\x03 \x01(\t\x12\r\n\x05start\x18\x04 \x01(\x03\x12\x0b\n\x03\x65nd\x18\x05 \x01(\x03\x12\x11\n\tpage_size\x18\x06 \x01(\x05\x12\x12\n\npage_token\x18\x07 \x01(\t\"S\n\x16SearchVariantsResponse\x12 \n\x08variants\x18\x01 \x03(\x0b\x32\x0e.ga4gh.Variant\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\"\'\n\x11GetVariantRequest\x12\x12\n\nvariant_id\x18\x01 \x01(\t\"d\n\x15SearchCallSetsRequest\x12\x16\n\x0evariant_set_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tpage_size\x18\x03 \x01(\x05\x12\x12\n\npage_token\x18\x04 \x01(\t\"T\n\x16SearchCallSetsResponse\x12!\n\tcall_sets\x18\x01 \x03(\x0b\x32\x0e.ga4gh.CallSet\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\"(\n\x11GetCallSetRequest\x12\x13\n\x0b\x63\x61ll_set_id\x18\x01 \x01(\t2\xb7\x03\n\x0eVariantService\x12V\n\x11SearchVariantSets\x12\x1f.ga4gh.SearchVariantSetsRequest\x1a .ga4gh.SearchVariantSetsResponse\x12?\n\rGetVariantSet\x12\x1b.ga4gh.GetVariantSetRequest\x1a\x11.ga4gh.VariantSet\x12M\n\x0eSearchVariants\x12\x1c.ga4gh.SearchVariantsRequest\x1a\x1d.ga4gh.SearchVariantsResponse\x12\x36\n\nGetVariant\x12\x18.ga4gh.GetVariantRequest\x1a\x0e.ga4gh.Variant\x12M\n\x0eSearchCallSets\x12\x1c.ga4gh.SearchCallSetsRequest\x1a\x1d.ga4gh.SearchCallSetsResponse\x12\x36\n\nGetCallSet\x12\x18.ga4gh.GetCallSetRequest\x1a\x0e.ga4gh.CallSetb\x06proto3'
  ,
  dependencies=[variants__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SEARCHVARIANTSETSREQUEST = _descriptor.Descriptor(
  name='SearchVariantSetsRequest',
  full_name='ga4gh.SearchVariantSetsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dataset_id', full_name='ga4gh.SearchVariantSetsRequest.dataset_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='page_size', full_name='ga4gh.SearchVariantSetsRequest.page_size', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='page_token', full_name='ga4gh.SearchVariantSetsRequest.page_token', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=133,
)


_SEARCHVARIANTSETSRESPONSE = _descriptor.Descriptor(
  name='SearchVariantSetsResponse',
  full_name='ga4gh.SearchVariantSetsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='variant_sets', full_name='ga4gh.SearchVariantSetsResponse.variant_sets', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='next_page_token', full_name='ga4gh.SearchVariantSetsResponse.next_page_token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=228,
)


_GETVARIANTSETREQUEST = _descriptor.Descriptor(
  name='GetVariantSetRequest',
  full_name='ga4gh.GetVariantSetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='variant_set_id', full_name='ga4gh.GetVariantSetRequest.variant_set_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=276,
)


_SEARCHVARIANTSREQUEST = _descriptor.Descriptor(
  name='SearchVariantsRequest',
  full_name='ga4gh.SearchVariantsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='variant_set_id', full_name='ga4gh.SearchVariantsRequest.variant_set_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='call_set_ids', full_name='ga4gh.SearchVariantsRequest.call_set_ids', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reference_name', full_name='ga4gh.SearchVariantsRequest.reference_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start', full_name='ga4gh.SearchVariantsRequest.start', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end', full_name='ga4gh.SearchVariantsRequest.end', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='page_size', full_name='ga4gh.SearchVariantsRequest.page_size', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='page_token', full_name='ga4gh.SearchVariantsRequest.page_token', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=279,
  serialized_end=439,
)


_SEARCHVARIANTSRESPONSE = _descriptor.Descriptor(
  name='SearchVariantsResponse',
  full_name='ga4gh.SearchVariantsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='variants', full_name='ga4gh.SearchVariantsResponse.variants', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='next_page_token', full_name='ga4gh.SearchVariantsResponse.next_page_token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=441,
  serialized_end=524,
)


_GETVARIANTREQUEST = _descriptor.Descriptor(
  name='GetVariantRequest',
  full_name='ga4gh.GetVariantRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='variant_id', full_name='ga4gh.GetVariantRequest.variant_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=526,
  serialized_end=565,
)


_SEARCHCALLSETSREQUEST = _descriptor.Descriptor(
  name='SearchCallSetsRequest',
  full_name='ga4gh.SearchCallSetsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='variant_set_id', full_name='ga4gh.SearchCallSetsRequest.variant_set_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='ga4gh.SearchCallSetsRequest.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='page_size', full_name='ga4gh.SearchCallSetsRequest.page_size', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='page_token', full_name='ga4gh.SearchCallSetsRequest.page_token', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=567,
  serialized_end=667,
)


_SEARCHCALLSETSRESPONSE = _descriptor.Descriptor(
  name='SearchCallSetsResponse',
  full_name='ga4gh.SearchCallSetsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='call_sets', full_name='ga4gh.SearchCallSetsResponse.call_sets', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='next_page_token', full_name='ga4gh.SearchCallSetsResponse.next_page_token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=669,
  serialized_end=753,
)


_GETCALLSETREQUEST = _descriptor.Descriptor(
  name='GetCallSetRequest',
  full_name='ga4gh.GetCallSetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='call_set_id', full_name='ga4gh.GetCallSetRequest.call_set_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=755,
  serialized_end=795,
)

_SEARCHVARIANTSETSRESPONSE.fields_by_name['variant_sets'].message_type = variants__pb2._VARIANTSET
_SEARCHVARIANTSRESPONSE.fields_by_name['variants'].message_type = variants__pb2._VARIANT
_SEARCHCALLSETSRESPONSE.fields_by_name['call_sets'].message_type = variants__pb2._CALLSET
DESCRIPTOR.message_types_by_name['SearchVariantSetsRequest'] = _SEARCHVARIANTSETSREQUEST
DESCRIPTOR.message_types_by_name['SearchVariantSetsResponse'] = _SEARCHVARIANTSETSRESPONSE
DESCRIPTOR.message_types_by_name['GetVariantSetRequest'] = _GETVARIANTSETREQUEST
DESCRIPTOR.message_types_by_name['SearchVariantsRequest'] = _SEARCHVARIANTSREQUEST
DESCRIPTOR.message_types_by_name['SearchVariantsResponse'] = _SEARCHVARIANTSRESPONSE
DESCRIPTOR.message_types_by_name['GetVariantRequest'] = _GETVARIANTREQUEST
DESCRIPTOR.message_types_by_name['SearchCallSetsRequest'] = _SEARCHCALLSETSREQUEST
DESCRIPTOR.message_types_by_name['SearchCallSetsResponse'] = _SEARCHCALLSETSRESPONSE
DESCRIPTOR.message_types_by_name['GetCallSetRequest'] = _GETCALLSETREQUEST

SearchVariantSetsRequest = _reflection.GeneratedProtocolMessageType('SearchVariantSetsRequest', (_message.Message,), dict(
  DESCRIPTOR = _SEARCHVARIANTSETSREQUEST,
  __module__ = 'variant_service_pb2'
  # @@protoc_insertion_point(class_scope:ga4gh.SearchVariantSetsRequest)
  ))
_sym_db.RegisterMessage(SearchVariantSetsRequest)

SearchVariantSetsResponse = _reflection.GeneratedProtocolMessageType('SearchVariantSetsResponse', (_message.Message,), dict(
  DESCRIPTOR = _SEARCHVARIANTSETSRESPONSE,
  __module__ = 'variant_service_pb2'
  # @@protoc_insertion_point(class_scope:ga4gh.SearchVariantSetsResponse)
  ))
_sym_db.RegisterMessage(SearchVariantSetsResponse)

GetVariantSetRequest = _reflection.GeneratedProtocolMessageType('GetVariantSetRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETVARIANTSETREQUEST,
  __module__ = 'variant_service_pb2'
  # @@protoc_insertion_point(class_scope:ga4gh.GetVariantSetRequest)
  ))
_sym_db.RegisterMessage(GetVariantSetRequest)

SearchVariantsRequest = _reflection.GeneratedProtocolMessageType('SearchVariantsRequest', (_message.Message,), dict(
  DESCRIPTOR = _SEARCHVARIANTSREQUEST,
  __module__ = 'variant_service_pb2'
  # @@protoc_insertion_point(class_scope:ga4gh.SearchVariantsRequest)
  ))
_sym_db.RegisterMessage(SearchVariantsRequest)

SearchVariantsResponse = _reflection.GeneratedProtocolMessageType('SearchVariantsResponse', (_message.Message,), dict(
  DESCRIPTOR = _SEARCHVARIANTSRESPONSE,
  __module__ = 'variant_service_pb2'
  # @@protoc_insertion_point(class_scope:ga4gh.SearchVariantsResponse)
  ))
_sym_db.RegisterMessage(SearchVariantsResponse)

GetVariantRequest = _reflection.GeneratedProtocolMessageType('GetVariantRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETVARIANTREQUEST,
  __module__ = 'variant_service_pb2'
  # @@protoc_insertion_point(class_scope:ga4gh.GetVariantRequest)
  ))
_sym_db.RegisterMessage(GetVariantRequest)

SearchCallSetsRequest = _reflection.GeneratedProtocolMessageType('SearchCallSetsRequest', (_message.Message,), dict(
  DESCRIPTOR = _SEARCHCALLSETSREQUEST,
  __module__ = 'variant_service_pb2'
  # @@protoc_insertion_point(class_scope:ga4gh.SearchCallSetsRequest)
  ))
_sym_db.RegisterMessage(SearchCallSetsRequest)

SearchCallSetsResponse = _reflection.GeneratedProtocolMessageType('SearchCallSetsResponse', (_message.Message,), dict(
  DESCRIPTOR = _SEARCHCALLSETSRESPONSE,
  __module__ = 'variant_service_pb2'
  # @@protoc_insertion_point(class_scope:ga4gh.SearchCallSetsResponse)
  ))
_sym_db.RegisterMessage(SearchCallSetsResponse)

GetCallSetRequest = _reflection.GeneratedProtocolMessageType('GetCallSetRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETCALLSETREQUEST,
  __module__ = 'variant_service_pb2'
  # @@protoc_insertion_point(class_scope:ga4gh.GetCallSetRequest)
  ))
_sym_db.RegisterMessage(GetCallSetRequest)


import abc
from grpc.beta import implementations as beta_implementations
from grpc.early_adopter import implementations as early_adopter_implementations
from grpc.framework.alpha import utilities as alpha_utilities
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities
class EarlyAdopterVariantServiceServicer(object):
  """<fill me in later!>"""
  __metaclass__ = abc.ABCMeta
  @abc.abstractmethod
  def SearchVariantSets(self, request, context):
    raise NotImplementedError()
  @abc.abstractmethod
  def GetVariantSet(self, request, context):
    raise NotImplementedError()
  @abc.abstractmethod
  def SearchVariants(self, request, context):
    raise NotImplementedError()
  @abc.abstractmethod
  def GetVariant(self, request, context):
    raise NotImplementedError()
  @abc.abstractmethod
  def SearchCallSets(self, request, context):
    raise NotImplementedError()
  @abc.abstractmethod
  def GetCallSet(self, request, context):
    raise NotImplementedError()
class EarlyAdopterVariantServiceServer(object):
  """<fill me in later!>"""
  __metaclass__ = abc.ABCMeta
  @abc.abstractmethod
  def start(self):
    raise NotImplementedError()
  @abc.abstractmethod
  def stop(self):
    raise NotImplementedError()
class EarlyAdopterVariantServiceStub(object):
  """<fill me in later!>"""
  __metaclass__ = abc.ABCMeta
  @abc.abstractmethod
  def SearchVariantSets(self, request):
    raise NotImplementedError()
  SearchVariantSets.async = None
  @abc.abstractmethod
  def GetVariantSet(self, request):
    raise NotImplementedError()
  GetVariantSet.async = None
  @abc.abstractmethod
  def SearchVariants(self, request):
    raise NotImplementedError()
  SearchVariants.async = None
  @abc.abstractmethod
  def GetVariant(self, request):
    raise NotImplementedError()
  GetVariant.async = None
  @abc.abstractmethod
  def SearchCallSets(self, request):
    raise NotImplementedError()
  SearchCallSets.async = None
  @abc.abstractmethod
  def GetCallSet(self, request):
    raise NotImplementedError()
  GetCallSet.async = None
def early_adopter_create_VariantService_server(servicer, port, private_key=None, certificate_chain=None):
  import variant_service_pb2
  import variant_service_pb2
  import variant_service_pb2
  import variants_pb2
  import variant_service_pb2
  import variant_service_pb2
  import variant_service_pb2
  import variants_pb2
  import variant_service_pb2
  import variant_service_pb2
  import variant_service_pb2
  import variants_pb2
  method_service_descriptions = {
    "GetCallSet": alpha_utilities.unary_unary_service_description(
      servicer.GetCallSet,
      variant_service_pb2.GetCallSetRequest.FromString,
      variants_pb2.CallSet.SerializeToString,
    ),
    "GetVariant": alpha_utilities.unary_unary_service_description(
      servicer.GetVariant,
      variant_service_pb2.GetVariantRequest.FromString,
      variants_pb2.Variant.SerializeToString,
    ),
    "GetVariantSet": alpha_utilities.unary_unary_service_description(
      servicer.GetVariantSet,
      variant_service_pb2.GetVariantSetRequest.FromString,
      variants_pb2.VariantSet.SerializeToString,
    ),
    "SearchCallSets": alpha_utilities.unary_unary_service_description(
      servicer.SearchCallSets,
      variant_service_pb2.SearchCallSetsRequest.FromString,
      variant_service_pb2.SearchCallSetsResponse.SerializeToString,
    ),
    "SearchVariantSets": alpha_utilities.unary_unary_service_description(
      servicer.SearchVariantSets,
      variant_service_pb2.SearchVariantSetsRequest.FromString,
      variant_service_pb2.SearchVariantSetsResponse.SerializeToString,
    ),
    "SearchVariants": alpha_utilities.unary_unary_service_description(
      servicer.SearchVariants,
      variant_service_pb2.SearchVariantsRequest.FromString,
      variant_service_pb2.SearchVariantsResponse.SerializeToString,
    ),
  }
  return early_adopter_implementations.server("ga4gh.VariantService", method_service_descriptions, port, private_key=private_key, certificate_chain=certificate_chain)
def early_adopter_create_VariantService_stub(host, port, metadata_transformer=None, secure=False, root_certificates=None, private_key=None, certificate_chain=None, server_host_override=None):
  import variant_service_pb2
  import variant_service_pb2
  import variant_service_pb2
  import variants_pb2
  import variant_service_pb2
  import variant_service_pb2
  import variant_service_pb2
  import variants_pb2
  import variant_service_pb2
  import variant_service_pb2
  import variant_service_pb2
  import variants_pb2
  method_invocation_descriptions = {
    "GetCallSet": alpha_utilities.unary_unary_invocation_description(
      variant_service_pb2.GetCallSetRequest.SerializeToString,
      variants_pb2.CallSet.FromString,
    ),
    "GetVariant": alpha_utilities.unary_unary_invocation_description(
      variant_service_pb2.GetVariantRequest.SerializeToString,
      variants_pb2.Variant.FromString,
    ),
    "GetVariantSet": alpha_utilities.unary_unary_invocation_description(
      variant_service_pb2.GetVariantSetRequest.SerializeToString,
      variants_pb2.VariantSet.FromString,
    ),
    "SearchCallSets": alpha_utilities.unary_unary_invocation_description(
      variant_service_pb2.SearchCallSetsRequest.SerializeToString,
      variant_service_pb2.SearchCallSetsResponse.FromString,
    ),
    "SearchVariantSets": alpha_utilities.unary_unary_invocation_description(
      variant_service_pb2.SearchVariantSetsRequest.SerializeToString,
      variant_service_pb2.SearchVariantSetsResponse.FromString,
    ),
    "SearchVariants": alpha_utilities.unary_unary_invocation_description(
      variant_service_pb2.SearchVariantsRequest.SerializeToString,
      variant_service_pb2.SearchVariantsResponse.FromString,
    ),
  }
  return early_adopter_implementations.stub("ga4gh.VariantService", method_invocation_descriptions, host, port, metadata_transformer=metadata_transformer, secure=secure, root_certificates=root_certificates, private_key=private_key, certificate_chain=certificate_chain, server_host_override=server_host_override)

class BetaVariantServiceServicer(object):
  """<fill me in later!>"""
  __metaclass__ = abc.ABCMeta
  @abc.abstractmethod
  def SearchVariantSets(self, request, context):
    raise NotImplementedError()
  @abc.abstractmethod
  def GetVariantSet(self, request, context):
    raise NotImplementedError()
  @abc.abstractmethod
  def SearchVariants(self, request, context):
    raise NotImplementedError()
  @abc.abstractmethod
  def GetVariant(self, request, context):
    raise NotImplementedError()
  @abc.abstractmethod
  def SearchCallSets(self, request, context):
    raise NotImplementedError()
  @abc.abstractmethod
  def GetCallSet(self, request, context):
    raise NotImplementedError()

class BetaVariantServiceStub(object):
  """The interface to which stubs will conform."""
  __metaclass__ = abc.ABCMeta
  @abc.abstractmethod
  def SearchVariantSets(self, request, timeout):
    raise NotImplementedError()
  SearchVariantSets.future = None
  @abc.abstractmethod
  def GetVariantSet(self, request, timeout):
    raise NotImplementedError()
  GetVariantSet.future = None
  @abc.abstractmethod
  def SearchVariants(self, request, timeout):
    raise NotImplementedError()
  SearchVariants.future = None
  @abc.abstractmethod
  def GetVariant(self, request, timeout):
    raise NotImplementedError()
  GetVariant.future = None
  @abc.abstractmethod
  def SearchCallSets(self, request, timeout):
    raise NotImplementedError()
  SearchCallSets.future = None
  @abc.abstractmethod
  def GetCallSet(self, request, timeout):
    raise NotImplementedError()
  GetCallSet.future = None

def beta_create_VariantService_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
  import variant_service_pb2
  import variant_service_pb2
  import variant_service_pb2
  import variants_pb2
  import variant_service_pb2
  import variant_service_pb2
  import variant_service_pb2
  import variants_pb2
  import variant_service_pb2
  import variant_service_pb2
  import variant_service_pb2
  import variants_pb2
  request_deserializers = {
    ('ga4gh.VariantService', 'GetCallSet'): variant_service_pb2.GetCallSetRequest.FromString,
    ('ga4gh.VariantService', 'GetVariant'): variant_service_pb2.GetVariantRequest.FromString,
    ('ga4gh.VariantService', 'GetVariantSet'): variant_service_pb2.GetVariantSetRequest.FromString,
    ('ga4gh.VariantService', 'SearchCallSets'): variant_service_pb2.SearchCallSetsRequest.FromString,
    ('ga4gh.VariantService', 'SearchVariantSets'): variant_service_pb2.SearchVariantSetsRequest.FromString,
    ('ga4gh.VariantService', 'SearchVariants'): variant_service_pb2.SearchVariantsRequest.FromString,
  }
  response_serializers = {
    ('ga4gh.VariantService', 'GetCallSet'): variants_pb2.CallSet.SerializeToString,
    ('ga4gh.VariantService', 'GetVariant'): variants_pb2.Variant.SerializeToString,
    ('ga4gh.VariantService', 'GetVariantSet'): variants_pb2.VariantSet.SerializeToString,
    ('ga4gh.VariantService', 'SearchCallSets'): variant_service_pb2.SearchCallSetsResponse.SerializeToString,
    ('ga4gh.VariantService', 'SearchVariantSets'): variant_service_pb2.SearchVariantSetsResponse.SerializeToString,
    ('ga4gh.VariantService', 'SearchVariants'): variant_service_pb2.SearchVariantsResponse.SerializeToString,
  }
  method_implementations = {
    ('ga4gh.VariantService', 'GetCallSet'): face_utilities.unary_unary_inline(servicer.GetCallSet),
    ('ga4gh.VariantService', 'GetVariant'): face_utilities.unary_unary_inline(servicer.GetVariant),
    ('ga4gh.VariantService', 'GetVariantSet'): face_utilities.unary_unary_inline(servicer.GetVariantSet),
    ('ga4gh.VariantService', 'SearchCallSets'): face_utilities.unary_unary_inline(servicer.SearchCallSets),
    ('ga4gh.VariantService', 'SearchVariantSets'): face_utilities.unary_unary_inline(servicer.SearchVariantSets),
    ('ga4gh.VariantService', 'SearchVariants'): face_utilities.unary_unary_inline(servicer.SearchVariants),
  }
  server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
  return beta_implementations.server(method_implementations, options=server_options)

def beta_create_VariantService_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
  import variant_service_pb2
  import variant_service_pb2
  import variant_service_pb2
  import variants_pb2
  import variant_service_pb2
  import variant_service_pb2
  import variant_service_pb2
  import variants_pb2
  import variant_service_pb2
  import variant_service_pb2
  import variant_service_pb2
  import variants_pb2
  request_serializers = {
    ('ga4gh.VariantService', 'GetCallSet'): variant_service_pb2.GetCallSetRequest.SerializeToString,
    ('ga4gh.VariantService', 'GetVariant'): variant_service_pb2.GetVariantRequest.SerializeToString,
    ('ga4gh.VariantService', 'GetVariantSet'): variant_service_pb2.GetVariantSetRequest.SerializeToString,
    ('ga4gh.VariantService', 'SearchCallSets'): variant_service_pb2.SearchCallSetsRequest.SerializeToString,
    ('ga4gh.VariantService', 'SearchVariantSets'): variant_service_pb2.SearchVariantSetsRequest.SerializeToString,
    ('ga4gh.VariantService', 'SearchVariants'): variant_service_pb2.SearchVariantsRequest.SerializeToString,
  }
  response_deserializers = {
    ('ga4gh.VariantService', 'GetCallSet'): variants_pb2.CallSet.FromString,
    ('ga4gh.VariantService', 'GetVariant'): variants_pb2.Variant.FromString,
    ('ga4gh.VariantService', 'GetVariantSet'): variants_pb2.VariantSet.FromString,
    ('ga4gh.VariantService', 'SearchCallSets'): variant_service_pb2.SearchCallSetsResponse.FromString,
    ('ga4gh.VariantService', 'SearchVariantSets'): variant_service_pb2.SearchVariantSetsResponse.FromString,
    ('ga4gh.VariantService', 'SearchVariants'): variant_service_pb2.SearchVariantsResponse.FromString,
  }
  cardinalities = {
    'GetCallSet': cardinality.Cardinality.UNARY_UNARY,
    'GetVariant': cardinality.Cardinality.UNARY_UNARY,
    'GetVariantSet': cardinality.Cardinality.UNARY_UNARY,
    'SearchCallSets': cardinality.Cardinality.UNARY_UNARY,
    'SearchVariantSets': cardinality.Cardinality.UNARY_UNARY,
    'SearchVariants': cardinality.Cardinality.UNARY_UNARY,
  }
  stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
  return beta_implementations.dynamic_stub(channel, 'ga4gh.VariantService', cardinalities, options=stub_options)
# @@protoc_insertion_point(module_scope)
