# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sequence_annotation_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import sequence_annotations_pb2 as sequence__annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sequence_annotation_service.proto',
  package='ga4gh',
  syntax='proto3',
  serialized_pb=b'\n!sequence_annotation_service.proto\x12\x05ga4gh\x1a\x1asequence_annotations.proto\"U\n\x18SearchFeatureSetsRequest\x12\x12\n\ndataset_id\x18\x01 \x01(\t\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t\"]\n\x19SearchFeatureSetsResponse\x12\'\n\x0c\x66\x65\x61ture_sets\x18\x01 \x03(\x0b\x32\x11.ga4gh.FeatureSet\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\".\n\x14GetFeatureSetRequest\x12\x16\n\x0e\x66\x65\x61ture_set_id\x18\x01 \x01(\t\"\xb4\x01\n\x15SearchFeaturesRequest\x12\x16\n\x0e\x66\x65\x61ture_set_id\x18\x01 \x01(\t\x12\x11\n\tparent_id\x18\x02 \x01(\t\x12\x16\n\x0ereference_name\x18\x03 \x01(\t\x12\r\n\x05start\x18\x04 \x01(\x03\x12\x0b\n\x03\x65nd\x18\x05 \x01(\x03\x12\x15\n\rfeature_types\x18\x06 \x03(\t\x12\x11\n\tpage_size\x18\x07 \x01(\x05\x12\x12\n\npage_token\x18\x08 \x01(\t\"S\n\x16SearchFeaturesResponse\x12 \n\x08\x66\x65\x61tures\x18\x01 \x03(\x0b\x32\x0e.ga4gh.Feature\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\"\'\n\x11GetFeatureRequest\x12\x12\n\nfeature_id\x18\x01 \x01(\t2\xbb\x02\n\x19SequenceAnnotationService\x12V\n\x11SearchFeatureSets\x12\x1f.ga4gh.SearchFeatureSetsRequest\x1a .ga4gh.SearchFeatureSetsResponse\x12?\n\rGetFeatureSet\x12\x1b.ga4gh.GetFeatureSetRequest\x1a\x11.ga4gh.FeatureSet\x12M\n\x0eSearchFeatures\x12\x1c.ga4gh.SearchFeaturesRequest\x1a\x1d.ga4gh.SearchFeaturesResponse\x12\x36\n\nGetFeature\x12\x18.ga4gh.GetFeatureRequest\x1a\x0e.ga4gh.Featureb\x06proto3'
  ,
  dependencies=[sequence__annotations__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SEARCHFEATURESETSREQUEST = _descriptor.Descriptor(
  name='SearchFeatureSetsRequest',
  full_name='ga4gh.SearchFeatureSetsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dataset_id', full_name='ga4gh.SearchFeatureSetsRequest.dataset_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='page_size', full_name='ga4gh.SearchFeatureSetsRequest.page_size', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='page_token', full_name='ga4gh.SearchFeatureSetsRequest.page_token', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=157,
)


_SEARCHFEATURESETSRESPONSE = _descriptor.Descriptor(
  name='SearchFeatureSetsResponse',
  full_name='ga4gh.SearchFeatureSetsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='feature_sets', full_name='ga4gh.SearchFeatureSetsResponse.feature_sets', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='next_page_token', full_name='ga4gh.SearchFeatureSetsResponse.next_page_token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=252,
)


_GETFEATURESETREQUEST = _descriptor.Descriptor(
  name='GetFeatureSetRequest',
  full_name='ga4gh.GetFeatureSetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='feature_set_id', full_name='ga4gh.GetFeatureSetRequest.feature_set_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=254,
  serialized_end=300,
)


_SEARCHFEATURESREQUEST = _descriptor.Descriptor(
  name='SearchFeaturesRequest',
  full_name='ga4gh.SearchFeaturesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='feature_set_id', full_name='ga4gh.SearchFeaturesRequest.feature_set_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parent_id', full_name='ga4gh.SearchFeaturesRequest.parent_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reference_name', full_name='ga4gh.SearchFeaturesRequest.reference_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start', full_name='ga4gh.SearchFeaturesRequest.start', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end', full_name='ga4gh.SearchFeaturesRequest.end', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='feature_types', full_name='ga4gh.SearchFeaturesRequest.feature_types', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='page_size', full_name='ga4gh.SearchFeaturesRequest.page_size', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='page_token', full_name='ga4gh.SearchFeaturesRequest.page_token', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=303,
  serialized_end=483,
)


_SEARCHFEATURESRESPONSE = _descriptor.Descriptor(
  name='SearchFeaturesResponse',
  full_name='ga4gh.SearchFeaturesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='features', full_name='ga4gh.SearchFeaturesResponse.features', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='next_page_token', full_name='ga4gh.SearchFeaturesResponse.next_page_token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=485,
  serialized_end=568,
)


_GETFEATUREREQUEST = _descriptor.Descriptor(
  name='GetFeatureRequest',
  full_name='ga4gh.GetFeatureRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='feature_id', full_name='ga4gh.GetFeatureRequest.feature_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=570,
  serialized_end=609,
)

_SEARCHFEATURESETSRESPONSE.fields_by_name['feature_sets'].message_type = sequence__annotations__pb2._FEATURESET
_SEARCHFEATURESRESPONSE.fields_by_name['features'].message_type = sequence__annotations__pb2._FEATURE
DESCRIPTOR.message_types_by_name['SearchFeatureSetsRequest'] = _SEARCHFEATURESETSREQUEST
DESCRIPTOR.message_types_by_name['SearchFeatureSetsResponse'] = _SEARCHFEATURESETSRESPONSE
DESCRIPTOR.message_types_by_name['GetFeatureSetRequest'] = _GETFEATURESETREQUEST
DESCRIPTOR.message_types_by_name['SearchFeaturesRequest'] = _SEARCHFEATURESREQUEST
DESCRIPTOR.message_types_by_name['SearchFeaturesResponse'] = _SEARCHFEATURESRESPONSE
DESCRIPTOR.message_types_by_name['GetFeatureRequest'] = _GETFEATUREREQUEST

SearchFeatureSetsRequest = _reflection.GeneratedProtocolMessageType('SearchFeatureSetsRequest', (_message.Message,), dict(
  DESCRIPTOR = _SEARCHFEATURESETSREQUEST,
  __module__ = 'sequence_annotation_service_pb2'
  # @@protoc_insertion_point(class_scope:ga4gh.SearchFeatureSetsRequest)
  ))
_sym_db.RegisterMessage(SearchFeatureSetsRequest)

SearchFeatureSetsResponse = _reflection.GeneratedProtocolMessageType('SearchFeatureSetsResponse', (_message.Message,), dict(
  DESCRIPTOR = _SEARCHFEATURESETSRESPONSE,
  __module__ = 'sequence_annotation_service_pb2'
  # @@protoc_insertion_point(class_scope:ga4gh.SearchFeatureSetsResponse)
  ))
_sym_db.RegisterMessage(SearchFeatureSetsResponse)

GetFeatureSetRequest = _reflection.GeneratedProtocolMessageType('GetFeatureSetRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETFEATURESETREQUEST,
  __module__ = 'sequence_annotation_service_pb2'
  # @@protoc_insertion_point(class_scope:ga4gh.GetFeatureSetRequest)
  ))
_sym_db.RegisterMessage(GetFeatureSetRequest)

SearchFeaturesRequest = _reflection.GeneratedProtocolMessageType('SearchFeaturesRequest', (_message.Message,), dict(
  DESCRIPTOR = _SEARCHFEATURESREQUEST,
  __module__ = 'sequence_annotation_service_pb2'
  # @@protoc_insertion_point(class_scope:ga4gh.SearchFeaturesRequest)
  ))
_sym_db.RegisterMessage(SearchFeaturesRequest)

SearchFeaturesResponse = _reflection.GeneratedProtocolMessageType('SearchFeaturesResponse', (_message.Message,), dict(
  DESCRIPTOR = _SEARCHFEATURESRESPONSE,
  __module__ = 'sequence_annotation_service_pb2'
  # @@protoc_insertion_point(class_scope:ga4gh.SearchFeaturesResponse)
  ))
_sym_db.RegisterMessage(SearchFeaturesResponse)

GetFeatureRequest = _reflection.GeneratedProtocolMessageType('GetFeatureRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETFEATUREREQUEST,
  __module__ = 'sequence_annotation_service_pb2'
  # @@protoc_insertion_point(class_scope:ga4gh.GetFeatureRequest)
  ))
_sym_db.RegisterMessage(GetFeatureRequest)


import abc
from grpc.beta import implementations as beta_implementations
from grpc.early_adopter import implementations as early_adopter_implementations
from grpc.framework.alpha import utilities as alpha_utilities
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities
class EarlyAdopterSequenceAnnotationServiceServicer(object):
  """<fill me in later!>"""
  __metaclass__ = abc.ABCMeta
  @abc.abstractmethod
  def SearchFeatureSets(self, request, context):
    raise NotImplementedError()
  @abc.abstractmethod
  def GetFeatureSet(self, request, context):
    raise NotImplementedError()
  @abc.abstractmethod
  def SearchFeatures(self, request, context):
    raise NotImplementedError()
  @abc.abstractmethod
  def GetFeature(self, request, context):
    raise NotImplementedError()
class EarlyAdopterSequenceAnnotationServiceServer(object):
  """<fill me in later!>"""
  __metaclass__ = abc.ABCMeta
  @abc.abstractmethod
  def start(self):
    raise NotImplementedError()
  @abc.abstractmethod
  def stop(self):
    raise NotImplementedError()
class EarlyAdopterSequenceAnnotationServiceStub(object):
  """<fill me in later!>"""
  __metaclass__ = abc.ABCMeta
  @abc.abstractmethod
  def SearchFeatureSets(self, request):
    raise NotImplementedError()
  SearchFeatureSets.async = None
  @abc.abstractmethod
  def GetFeatureSet(self, request):
    raise NotImplementedError()
  GetFeatureSet.async = None
  @abc.abstractmethod
  def SearchFeatures(self, request):
    raise NotImplementedError()
  SearchFeatures.async = None
  @abc.abstractmethod
  def GetFeature(self, request):
    raise NotImplementedError()
  GetFeature.async = None
def early_adopter_create_SequenceAnnotationService_server(servicer, port, private_key=None, certificate_chain=None):
  import sequence_annotation_service_pb2
  import sequence_annotation_service_pb2
  import sequence_annotation_service_pb2
  import sequence_annotations_pb2
  import sequence_annotation_service_pb2
  import sequence_annotation_service_pb2
  import sequence_annotation_service_pb2
  import sequence_annotations_pb2
  method_service_descriptions = {
    "GetFeature": alpha_utilities.unary_unary_service_description(
      servicer.GetFeature,
      sequence_annotation_service_pb2.GetFeatureRequest.FromString,
      sequence_annotations_pb2.Feature.SerializeToString,
    ),
    "GetFeatureSet": alpha_utilities.unary_unary_service_description(
      servicer.GetFeatureSet,
      sequence_annotation_service_pb2.GetFeatureSetRequest.FromString,
      sequence_annotations_pb2.FeatureSet.SerializeToString,
    ),
    "SearchFeatureSets": alpha_utilities.unary_unary_service_description(
      servicer.SearchFeatureSets,
      sequence_annotation_service_pb2.SearchFeatureSetsRequest.FromString,
      sequence_annotation_service_pb2.SearchFeatureSetsResponse.SerializeToString,
    ),
    "SearchFeatures": alpha_utilities.unary_unary_service_description(
      servicer.SearchFeatures,
      sequence_annotation_service_pb2.SearchFeaturesRequest.FromString,
      sequence_annotation_service_pb2.SearchFeaturesResponse.SerializeToString,
    ),
  }
  return early_adopter_implementations.server("ga4gh.SequenceAnnotationService", method_service_descriptions, port, private_key=private_key, certificate_chain=certificate_chain)
def early_adopter_create_SequenceAnnotationService_stub(host, port, metadata_transformer=None, secure=False, root_certificates=None, private_key=None, certificate_chain=None, server_host_override=None):
  import sequence_annotation_service_pb2
  import sequence_annotation_service_pb2
  import sequence_annotation_service_pb2
  import sequence_annotations_pb2
  import sequence_annotation_service_pb2
  import sequence_annotation_service_pb2
  import sequence_annotation_service_pb2
  import sequence_annotations_pb2
  method_invocation_descriptions = {
    "GetFeature": alpha_utilities.unary_unary_invocation_description(
      sequence_annotation_service_pb2.GetFeatureRequest.SerializeToString,
      sequence_annotations_pb2.Feature.FromString,
    ),
    "GetFeatureSet": alpha_utilities.unary_unary_invocation_description(
      sequence_annotation_service_pb2.GetFeatureSetRequest.SerializeToString,
      sequence_annotations_pb2.FeatureSet.FromString,
    ),
    "SearchFeatureSets": alpha_utilities.unary_unary_invocation_description(
      sequence_annotation_service_pb2.SearchFeatureSetsRequest.SerializeToString,
      sequence_annotation_service_pb2.SearchFeatureSetsResponse.FromString,
    ),
    "SearchFeatures": alpha_utilities.unary_unary_invocation_description(
      sequence_annotation_service_pb2.SearchFeaturesRequest.SerializeToString,
      sequence_annotation_service_pb2.SearchFeaturesResponse.FromString,
    ),
  }
  return early_adopter_implementations.stub("ga4gh.SequenceAnnotationService", method_invocation_descriptions, host, port, metadata_transformer=metadata_transformer, secure=secure, root_certificates=root_certificates, private_key=private_key, certificate_chain=certificate_chain, server_host_override=server_host_override)

class BetaSequenceAnnotationServiceServicer(object):
  """<fill me in later!>"""
  __metaclass__ = abc.ABCMeta
  @abc.abstractmethod
  def SearchFeatureSets(self, request, context):
    raise NotImplementedError()
  @abc.abstractmethod
  def GetFeatureSet(self, request, context):
    raise NotImplementedError()
  @abc.abstractmethod
  def SearchFeatures(self, request, context):
    raise NotImplementedError()
  @abc.abstractmethod
  def GetFeature(self, request, context):
    raise NotImplementedError()

class BetaSequenceAnnotationServiceStub(object):
  """The interface to which stubs will conform."""
  __metaclass__ = abc.ABCMeta
  @abc.abstractmethod
  def SearchFeatureSets(self, request, timeout):
    raise NotImplementedError()
  SearchFeatureSets.future = None
  @abc.abstractmethod
  def GetFeatureSet(self, request, timeout):
    raise NotImplementedError()
  GetFeatureSet.future = None
  @abc.abstractmethod
  def SearchFeatures(self, request, timeout):
    raise NotImplementedError()
  SearchFeatures.future = None
  @abc.abstractmethod
  def GetFeature(self, request, timeout):
    raise NotImplementedError()
  GetFeature.future = None

def beta_create_SequenceAnnotationService_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
  import sequence_annotation_service_pb2
  import sequence_annotation_service_pb2
  import sequence_annotation_service_pb2
  import sequence_annotations_pb2
  import sequence_annotation_service_pb2
  import sequence_annotation_service_pb2
  import sequence_annotation_service_pb2
  import sequence_annotations_pb2
  request_deserializers = {
    ('ga4gh.SequenceAnnotationService', 'GetFeature'): sequence_annotation_service_pb2.GetFeatureRequest.FromString,
    ('ga4gh.SequenceAnnotationService', 'GetFeatureSet'): sequence_annotation_service_pb2.GetFeatureSetRequest.FromString,
    ('ga4gh.SequenceAnnotationService', 'SearchFeatureSets'): sequence_annotation_service_pb2.SearchFeatureSetsRequest.FromString,
    ('ga4gh.SequenceAnnotationService', 'SearchFeatures'): sequence_annotation_service_pb2.SearchFeaturesRequest.FromString,
  }
  response_serializers = {
    ('ga4gh.SequenceAnnotationService', 'GetFeature'): sequence_annotations_pb2.Feature.SerializeToString,
    ('ga4gh.SequenceAnnotationService', 'GetFeatureSet'): sequence_annotations_pb2.FeatureSet.SerializeToString,
    ('ga4gh.SequenceAnnotationService', 'SearchFeatureSets'): sequence_annotation_service_pb2.SearchFeatureSetsResponse.SerializeToString,
    ('ga4gh.SequenceAnnotationService', 'SearchFeatures'): sequence_annotation_service_pb2.SearchFeaturesResponse.SerializeToString,
  }
  method_implementations = {
    ('ga4gh.SequenceAnnotationService', 'GetFeature'): face_utilities.unary_unary_inline(servicer.GetFeature),
    ('ga4gh.SequenceAnnotationService', 'GetFeatureSet'): face_utilities.unary_unary_inline(servicer.GetFeatureSet),
    ('ga4gh.SequenceAnnotationService', 'SearchFeatureSets'): face_utilities.unary_unary_inline(servicer.SearchFeatureSets),
    ('ga4gh.SequenceAnnotationService', 'SearchFeatures'): face_utilities.unary_unary_inline(servicer.SearchFeatures),
  }
  server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
  return beta_implementations.server(method_implementations, options=server_options)

def beta_create_SequenceAnnotationService_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
  import sequence_annotation_service_pb2
  import sequence_annotation_service_pb2
  import sequence_annotation_service_pb2
  import sequence_annotations_pb2
  import sequence_annotation_service_pb2
  import sequence_annotation_service_pb2
  import sequence_annotation_service_pb2
  import sequence_annotations_pb2
  request_serializers = {
    ('ga4gh.SequenceAnnotationService', 'GetFeature'): sequence_annotation_service_pb2.GetFeatureRequest.SerializeToString,
    ('ga4gh.SequenceAnnotationService', 'GetFeatureSet'): sequence_annotation_service_pb2.GetFeatureSetRequest.SerializeToString,
    ('ga4gh.SequenceAnnotationService', 'SearchFeatureSets'): sequence_annotation_service_pb2.SearchFeatureSetsRequest.SerializeToString,
    ('ga4gh.SequenceAnnotationService', 'SearchFeatures'): sequence_annotation_service_pb2.SearchFeaturesRequest.SerializeToString,
  }
  response_deserializers = {
    ('ga4gh.SequenceAnnotationService', 'GetFeature'): sequence_annotations_pb2.Feature.FromString,
    ('ga4gh.SequenceAnnotationService', 'GetFeatureSet'): sequence_annotations_pb2.FeatureSet.FromString,
    ('ga4gh.SequenceAnnotationService', 'SearchFeatureSets'): sequence_annotation_service_pb2.SearchFeatureSetsResponse.FromString,
    ('ga4gh.SequenceAnnotationService', 'SearchFeatures'): sequence_annotation_service_pb2.SearchFeaturesResponse.FromString,
  }
  cardinalities = {
    'GetFeature': cardinality.Cardinality.UNARY_UNARY,
    'GetFeatureSet': cardinality.Cardinality.UNARY_UNARY,
    'SearchFeatureSets': cardinality.Cardinality.UNARY_UNARY,
    'SearchFeatures': cardinality.Cardinality.UNARY_UNARY,
  }
  stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
  return beta_implementations.dynamic_stub(channel, 'ga4gh.SequenceAnnotationService', cardinalities, options=stub_options)
# @@protoc_insertion_point(module_scope)
